// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD09oJCZNMXSDSWgkEv0Cykwk2lLtPrikY',
    appId: '1:417069245050:web:d91eb0e51bbc29a69b11c3',
    messagingSenderId: '417069245050',
    projectId: 'course-motobike-48876',
    authDomain: 'course-motobike-48876.firebaseapp.com',
    storageBucket: 'course-motobike-48876.firebasestorage.app',
    measurementId: 'G-ZCYSQ8E1SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYtaBzLQCDWV5op64sRf3sUZG41l-sPM',
    appId: '1:417069245050:android:a7a385573399be309b11c3',
    messagingSenderId: '417069245050',
    projectId: 'course-motobike-48876',
    storageBucket: 'course-motobike-48876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMXykbLFwV4vUO04yExhZjO1FMgMEAYcg',
    appId: '1:417069245050:ios:1675e5d03b90f9509b11c3',
    messagingSenderId: '417069245050',
    projectId: 'course-motobike-48876',
    storageBucket: 'course-motobike-48876.firebasestorage.app',
    iosBundleId: 'com.example.courseMotobike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMXykbLFwV4vUO04yExhZjO1FMgMEAYcg',
    appId: '1:417069245050:ios:1675e5d03b90f9509b11c3',
    messagingSenderId: '417069245050',
    projectId: 'course-motobike-48876',
    storageBucket: 'course-motobike-48876.firebasestorage.app',
    iosBundleId: 'com.example.courseMotobike',
  );
}
